version: 2
updates:
  - package-ecosystem: "gomod" # or another package manager
    directory: "/" # Location of package files
    schedule:
      interval: "daily"
    target-branch: "main" # Target your new branch here