name: CI for Dependabot

on:
  pull_request:
    branches:
      - dependabot
    paths:
      - 'go.mod'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go  # Specify the language(s) your project uses

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...