name: CI for Dependabot

on:
  push:
    branches:
      - dependabot  # Your target branch
  pull_request:
    branches:
      - dependabot  # Your target branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...